server.port=9090
#spring.application.name=authentication


spring.data.mongodb.uri=${DATABASE_URI}
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017


#jwt.access.secret=${ACCESS_TOKEN_SECRET}
#jwt.refresh.secret=${REFRESH_TOKEN_SECRET}
#jwt.privateKey=${JWT_PRIVATE_KEY}
#jwt.publicKey=${JWT_PUBLIC_KEY}
#jwt.privateKeyPath=${JWT_PRIVATE_KEY_PATH}
#jwt.publicKeyPath=${JWT_PUBLIC_KEY_PATH}
#path from environment or default
jwt.privateKeyPath=${JWT_PRIVATE_KEY_PATH:./config/keys/private.pem}
jwt.publicKeyPath=${JWT_PUBLIC_KEY_PATH:./config/keys/public.pem}
# 10 minutes
jwt.expiration.ms= 600000
# 1 days
jwt.refresh.expiration.ms= 86400000


cors.allowed-origins=http://localhost:9090,http://127.0.0.1:5500,http://localhost:3500,https://localhost:3500,https://localhost:3000,http://localhost:3000,https://login-register-ui-demo.netlify.app

logging.file.name=logs/history-logging.log
logging.level.root=INFO
logging.level.com.jwt=DEBUG

# Cookie config
jwt.cookie.refreshTokenName=refreshToken
jwt.cookie.accessTokenName=accessToken
jwt.cookie.path=/
jwt.cookie.http-only=true
jwt.cookie.secure=false
jwt.cookie.same-site=Lax
jwt.cookie.max-age=604800


