server.port=9090
#spring.application.name=authentication


spring.data.mongodb.uri=${DATABASE_URI}
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017


jwt.access.secret=${ACCESS_TOKEN_SECRET}
jwt.refresh.secret=${REFRESH_TOKEN_SECRET}
jwt.expiration.ms= 86400000


cors.allowed-origins=http://localhost:9090,http://127.0.0.1:5500,http://localhost:3500,https://localhost:3500,https://localhost:3000,http://localhost:3000,https://login-register-ui-demo.netlify.app

logging.file.name=logs/history-logging.log
logging.level.root=INFO
logging.level.com.jwt=DEBUG




